name: Dirty Chai
favicon: null
layout_spectrum: 0
typography_spectrum: 0.14911
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5f605c'
    - '#262626'
    - '#919493'
    - '#a9cbc7'
    - '#4c8169'
  brandStrength: 0
  lightness: 0.1875
  saturation: 0.0625
  rhythmicContrast: 0.5
purpose: []
