name: Dirty Chai
favicon: null
layout_spectrum: 0
typography_spectrum: 0.14911
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ede9e6'
    - '#4d8a8b'
    - '#c2c4c3'
    - '#000404'
    - '#546362'
  brandStrength: 0
  lightness: 0.1875
  saturation: 0.0625
  rhythmicContrast: 0.5
purpose: []
