name: Dirty Chai
favicon: null
layout_spectrum: 1
typography_spectrum: 0.73181
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fefefe'
    - '#9e988c'
    - '#605c53'
    - '#e9d6b8'
  brandStrength: 0
  lightness: 0
  saturation: 0.125
  rhythmicContrast: 1
purpose: []
